// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package storage

import ()

type Image struct {
	ID        int64
	Url       string
	Nsfw      int64
	Nsfwlevel string
	Prompt    string
	Width     int64
	Height    int64
	Score     int64
}

type ImagesTag struct {
	ImageID int64
	TagID   int64
}

type Tag struct {
	ID      int64
	Content string
}
